
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Strawberry/c/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 6.2.9200 - AMD64
...
